apiVersion: apps/v1
kind: Deployment
metadata:
  name: hau-eks-backend-deployment
  namespace: hau-eks-backend-app
  labels:
    app: hau-backend-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hau-backend-app
  template:
    metadata:
      labels:
        app: hau-backend-app
    spec:
      containers:
      - name: backend-server
        image: 492804330065.dkr.ecr.us-west-2.amazonaws.com/hau-todo-be:6.0
        ports:
        - name: server-port
          containerPort: 5000
        imagePullPolicy: Always
        env:
        # - name : WEBSITE_PORT
        #   value : "5000"
        - name : POSTGRES_HOST
          value : "hau-db-instance.c55toqx3dgp6.us-east-2.rds.amazonaws.com"
        # - name : POSTGRES_DATABASE
        #   value : "perntodo"
        - name : POSTGRES_USER
          value : "postgres"
        - name : POSTGRES_PASSWORD
          value : "<yFglvZmIKj8md#3"
      nodeSelector:
        kubernetes.io/os: linux